# .github/workflows/deploy-ngrok.yml
name: Deploy ngrok endpoint

on:
  push:
    branches: [ deployment ]

jobs:
  deploy:
    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/ngrok-endpoint.yml
    with:
      config_path: ".ngrok/configs/prod.yml"           # overrides CONFIG_PATH
      policy_path: ".ngrok/policies/prod.yml"         # optional, skip if auto-detect
      base_branch: "main"                              # where PRs are opened
      ngrok_api_url: "https://api.ngrok.com/endpoints" # optional override
      ngrok_api_version: "2"                           # optional override
      auto_merge: true                                 # toggle auto-merge
    secrets:
      NGROK_API_TOKEN: ${{ secrets.NGROK_API_TOKEN }}
