name: Create ngrok Endpoint (deployment branch)

on:
  push:
    branches: [ deployment ]

permissions:
  contents: read

env:
  NGROK_API_URL: https://api.ngrok.com/endpoints
  NGROK_API_VERSION: "2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production   # <- uncomment if you’re using an Environment secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure required files exist
        run: |
          set -e
          test -f config.yml || { echo "::error::Missing config.yml in branch"; exit 1; }
          test -f policy.yml || { echo "::error::Missing policy.yml in branch"; exit 1; }

      - name: Install tools (yq, jq)
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y -qq jq >/dev/null
          yq --version
          jq --version

      - name: Validate and read config.yml
        id: cfg
        shell: bash
        run: |
          set -euo pipefail

          # Required fields
          URL=$(yq -r '.url // ""'  config.yml)
          TYPE=$(yq -r '.type // ""' config.yml)

          if [[ -z "$URL" ]]; then
            echo "::error::config.yml is missing required key: url"
            exit 1
          fi
          if [[ -z "$TYPE" ]]; then
            echo "::error::config.yml is missing required key: type"
            exit 1
          fi

          # Optional fields (empty string if absent)
          DESC=$(yq -r '.description // ""' config.yml)
          META=$(yq -r '.metadata // ""'    config.yml)
          # boolean -> string if present, else ""
          POOL=$(yq -r '(.pooling_enabled // "") | tostring' config.yml)

          {
            echo "url<<__EOF__";  echo -n "$URL";  echo; echo "__EOF__"
            echo "type=$TYPE"
            echo "desc<<__EOF__"; echo -n "$DESC"; echo; echo "__EOF__"
            echo "meta<<__EOF__"; echo -n "$META"; echo; echo "__EOF__"
            echo "pool=$POOL"
          } >> "$GITHUB_OUTPUT"

      - name: Build traffic policy from policy.yml (YAML or JSON -> JSON)
        id: policy
        shell: bash
        run: |
          set -euo pipefail

          # If file is valid JSON, compact it; otherwise parse YAML -> JSON
          if jq -e . policy.yml >/dev/null 2>&1; then
            jq -c . policy.yml > /tmp/policy.json
          else
            yq -o=json -I=0 '.' policy.yml > /tmp/policy.json
          fi

          # single-line, no trailing newline
          tr -d '\n' < /tmp/policy.json > /tmp/policy.json.tmp && mv /tmp/policy.json.tmp /tmp/policy.json

          {
            echo "path=/tmp/policy.json"
          } >> "$GITHUB_OUTPUT"

      - name: Call ngrok API (create Endpoint)
        env:
          TOKEN: ${{ secrets.NGROK_API_TOKEN }}   # Environment or Repo secret
        shell: bash
        run: |
          set -euo pipefail
          echo "::add-mask::${TOKEN}"

          # Build args
          DATA=(
            --data-urlencode "url=${{ steps.cfg.outputs.url }}"
            --data-urlencode "type=${{ steps.cfg.outputs.type }}"
            # Read JSON from file so we avoid shell-quoting issues
            --data-urlencode "traffic_policy@${{ steps.policy.outputs.path }}"
          )

          if [[ -n "${{ steps.cfg.outputs.desc }}" ]]; then
            DATA+=( --data-urlencode "description=${{ steps.cfg.outputs.desc }}" )
          fi
          if [[ -n "${{ steps.cfg.outputs.meta }}" ]]; then
            DATA+=( --data-urlencode "metadata=${{ steps.cfg.outputs.meta }}" )
          fi
          if [[ -n "${{ steps.cfg.outputs.pool }}" ]]; then
            DATA+=( --data-urlencode "pooling_enabled=${{ steps.cfg.outputs.pool }}" )
          fi

          # ----- Preview (token redacted) -----
          {
            echo "About to run this request:"
            printf "curl --location %q \\\n" "${NGROK_API_URL}"
            printf "  --header %q \\\n" "Content-Type: application/x-www-form-urlencoded"
            printf "  --header %q \\\n" "Ngrok-Version: ${NGROK_API_VERSION}"
            printf "  --header %q \\\n" "Authorization: Bearer ***REDACTED***"
            for arg in "${DATA[@]}"; do
              printf "  %q \\\n" "$arg"
            done
            echo "  --silent --show-error --write-out '%{http_code}'"
          } 1>&2
          # ------------------------------------

          # Send request
          HTTP_CODE=$(
            curl -sS -w "%{http_code}" -o /tmp/resp.json \
              --location "${NGROK_API_URL}" \
              --header "Content-Type: application/x-www-form-urlencoded" \
              --header "Ngrok-Version: ${NGROK_API_VERSION}" \
              --header "Authorization: Bearer ${TOKEN}" \
              "${DATA[@]}"
          )

          echo "HTTP ${HTTP_CODE}"
          (jq -C . /tmp/resp.json || cat /tmp/resp.json)

          if [[ "${HTTP_CODE}" -lt 200 || "${HTTP_CODE}" -ge 300 ]]; then
            echo "::error::ngrok API returned HTTP ${HTTP_CODE}"
            exit 1
          fi
